### Numpy
- Scientific library
- Support large number of data in the form of multi dimensional array and matrix
- Used for mathematic calculation
- Num is stand for Numeric and Py is stand for Python
- Numpy Link : https://numpy.org/doc/stable/reference/index.html

### Numpy for ML
- In ML, with the help of images we predict new output ex:- object detection
- For detecting object we gives images to ML but ML can't read images directly that's why we convert images in numeric format than we convert numeric data into Numpy array, Theirfor object is detected.

# Creating Numpy Array 
## One Dimention Array 
ex :- [1,2,3]

In [2]:
import numpy as np

In [3]:
num = [1,2,3]
num = np.array(num)
num

array([1, 2, 3])

In [4]:
num.shape

(3,)

## Two Dimention Array
ex :- [[1,2,3],
       [4,5,6],
       [7,8,9]]

In [5]:
num = [[1,2,3],[4,5,6]]
num = np.array(num)
num

array([[1, 2, 3],
       [4, 5, 6]])

## Three Dimention Array
ex :- [[[ 1, 2, 3],
        [ 4, 5, 6],
        [ 7, 8, 9]],
       [[11,12,13],
        [14,15,16],
        [17,18,19]],
       [[21,22,23],
        [24,25,26],
        [27,28,29]]]

In [6]:
num = [[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]
num = np.array(num)
num

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [7]:
num.ndim #check array dimention

3

In [8]:
num.dtype #check array data type

dtype('int32')

In [9]:
num.shape #check array shape

(2, 2, 3)

In [10]:
num = [1,2,3,4]
num = np.array(num)
num.size #check no of element in array

4

In [11]:
#changing data by putting one diff value
num = [1,2,3.0]
num = np.array(num)
print(num)
num.dtype

[1. 2. 3.]


dtype('float64')

In [12]:
num = [1,2,'3']
num = np.array(num)
print(num)
num.dtype

['1' '2' '3']


dtype('<U11')

# Create Numpy Array Using Numpy Method (Function) 
## zeros,ones,eye,diag,randint,rand,randn

In [13]:
#zeros:- print 0. at all position
arr = np.zeros(5)#1D array
arr

array([0., 0., 0., 0., 0.])

In [14]:
arra = np.zeros((2,3))#2D array
arra

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
#ones:- print 1. at all position
arr = np.ones(4)#1D array
arr

array([1., 1., 1., 1.])

In [16]:
arra = np.ones((2,3))#2D array
arra

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
#eye:- print 1. at diagonal
arr = np.eye(4)#2D array 4x4 matrix
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
arr = np.eye(3,4)#2D array 3x4 matrix
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [19]:
#diag:- print input at diagonal
arr = np.diag([1,2,3,4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [20]:
#for check diagonal of matrix
np.diag(arr)

array([1, 2, 3, 4])

In [21]:
#randint:- gives random no's
arr = np.random.randint(10,45,14)#4 no's b/w 1 to 15,not considering 15
arr

array([23, 10, 31, 20, 17, 17, 14, 15, 14, 38, 14, 34, 16, 16])

In [22]:
#rand:- gives random no's b/w 0 to 1, no's taken from uniform distribution
arr = np.random.rand(6)# 1D array
arr


array([0.87844431, 0.53007585, 0.93204448, 0.5493862 , 0.06592337,
       0.35979544])

In [23]:
arra = np.random.rand(10)
arra

array([0.9158939 , 0.61990014, 0.28878231, 0.36039081, 0.07461635,
       0.84746296, 0.63019789, 0.63529295, 0.85670612, 0.6012533 ])

In [24]:
arr = np.random.rand(2,3)#2D array 2x3 matrix
arr

array([[0.62084713, 0.22304269, 0.90512186],
       [0.25194488, 0.80243945, 0.6341168 ]])

In [25]:
#randn:- give random float no's,mean centered to '0' (nearly '0'),variance nearly '1' no's taken from std normal distribution
arr = np.random.randn(4) #1D array
print(arr)
np.mean(arr)#mean value in randn

[-0.72559611 -0.10839137  0.05983626  0.02753592]


-0.18665382461103547

In [26]:
np.var(arr)#variance value in randn

0.10080460177978559

## Reshaping of data:- changing array from 1D,2D,3D to 2D/3D,1D/3D,1D/2D respectively 

In [27]:
#reshaping data:- product of no of element in reshape array is equal to total element in previous array
arr = np.random.randint(1,100,20)# total element = 20 
print(arr)
print(arr.ndim)
print(arr.shape)

arr = arr.reshape(2,10) # product = 2*10=20
print(arr)
print(arr.ndim)
print(arr.shape)

arr = arr.reshape(2,2,5) #2*2*5=20
print(arr)
print(arr.ndim)
print(arr.shape)


[72 78 38 55 84 13 78 99 86 82 38 76 83 69 95 37 38 79 86  3]
1
(20,)
[[72 78 38 55 84 13 78 99 86 82]
 [38 76 83 69 95 37 38 79 86  3]]
2
(2, 10)
[[[72 78 38 55 84]
  [13 78 99 86 82]]

 [[38 76 83 69 95]
  [37 38 79 86  3]]]
3
(2, 2, 5)


In [28]:
import numpy as np

In [30]:
# -1 in reshaping:- 
arr = np.arange(1,21)#20 element,not consider 21
print(arr)
print(arr.reshape(2,10))# 2*10=20,2 row 10 column
print(arr.reshape(5,-1))#gives 5 row
print(arr.reshape(4,-1))#gives 4 row
print(arr.reshape(10,-1))#gives 10 row

print(arr.reshape(-1,4))#gives 4 column
print(arr.reshape(-1,5))#gives 5 column
print(arr.reshape(-1,10))#gives 10 column

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


## seed function:- use for getting same random no in array for all, declaring before declaration of array


In [31]:
arr = np.random.randint(1,101,10)
print(arr)

[51  9 18 22  8 57  7 90 34 91]


In [32]:
np.random.seed(5) #same for all
arr = np.random.randint(1,101,10)
print(arr)

[100  79  62  17  74   9  63  28  31  81]


## Indexing and Slicing of 1D Array 

In [33]:
import numpy as np
arr = np.array([5,10,15,20,25])
arr

array([ 5, 10, 15, 20, 25])

In [34]:
#indexing:-positioning of array element
arr[3]#indexing

20

In [35]:
arr[4]

25

In [36]:
arr[-1]

25

In [37]:
arr[-4]

10

In [38]:
#slicing:-it gives smoll array from given array
arr[0:2]#it gives element index 0 to 1 not consider index 2

array([ 5, 10])

In [39]:
arr[:3]# from 0 index to 3 index

array([ 5, 10, 15])

In [40]:
arr[1:4]

array([10, 15, 20])

In [41]:
arr[-4:-1]

array([10, 15, 20])

In [42]:
arr[-5:]

array([ 5, 10, 15, 20, 25])

In [43]:
arr[:]

array([ 5, 10, 15, 20, 25])

In [44]:
arr[1:4]

array([10, 15, 20])

In [45]:
arr[1:4:2]#skip one step

array([10, 20])

In [46]:
arr[0:5]

array([ 5, 10, 15, 20, 25])

In [47]:
arr[0:5:3]

array([ 5, 20])

In [48]:
arr[::-1]#revers the array

array([25, 20, 15, 10,  5])

In [49]:
arr[::-4]#skip 3 element

array([25,  5])

In [50]:
arr[2::]

array([15, 20, 25])

In [51]:
arr[1::]

array([10, 15, 20, 25])

## Indexing and Slicing of 2D Array

In [52]:
#Create 2D array
import numpy as np

In [53]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [54]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [55]:
#indexing using double bracket notation
matrix[0][2]

15

In [56]:
matrix[2][2]

45

In [57]:
#indexing using single bracket notation
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [58]:
matrix[0,2]

15

In [59]:
matrix[2,2]

45

In [60]:
#slicing using single bracket notation
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [61]:
#  [[5,10],
#   [20,25]]
matrix[ :2, :2]

array([[ 5, 10],
       [20, 25]])

In [62]:
matrix[1: ,1: ]

array([[25, 30],
       [40, 45]])

In [63]:
np.random.seed(123)
matrix2 = np.random.randint(1,101,25).reshape(5,5)
matrix2

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [64]:
matrix2[1:4,1:4]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])

In [65]:
matrix2[4: ,2: ]

array([[56, 68,  3]])

In [66]:
#broad casting in numpy:-change the vlaue of array element
array = np.array([5,10,15,20,25,40,35,40])
array

array([ 5, 10, 15, 20, 25, 40, 35, 40])

In [67]:
array[2:5] = 0
array

array([ 5, 10,  0,  0,  0, 40, 35, 40])

## View and Copy 

In [68]:
import numpy as np

In [69]:
arr = np.array([5,10,15,20,25,30])
arr

array([ 5, 10, 15, 20, 25, 30])

In [70]:
sliced_arr = arr[2:5]#view array of 'arr'

In [71]:
sliced_arr

array([15, 20, 25])

In [72]:
sliced_arr[:] = 0
sliced_arr #this also change the value of 'arr' 

array([0, 0, 0])

In [73]:
sliced_arr

array([0, 0, 0])

In [74]:
arr

array([ 5, 10,  0,  0,  0, 30])

In [75]:
array = np.array([5,10,15,20,25,30])
array

array([ 5, 10, 15, 20, 25, 30])

In [76]:
co_arr = array[2:5].copy()   #copy array of'arr'

In [77]:
co_arr

array([15, 20, 25])

## Condition section:-use conditions in array


In [78]:
import numpy as np

In [79]:
array = np.arange(1,11)

In [80]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr>5

array([False,  True, False, False, False,  True])

In [82]:
mask = array>5

In [83]:
array[mask]

array([ 6,  7,  8,  9, 10])

In [84]:
array[array<4]

array([1, 2, 3])

In [85]:
array[array%2==0]

array([ 2,  4,  6,  8, 10])

In [86]:
array[array==5]

array([5])

In [87]:
array[array%2==0]=0
array

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

## operation on array with scaler 

In [88]:
#how we perforn numerical opertion of using one array and one number
import numpy as np

In [89]:
arr = np.array([1,2,3,4])

In [90]:
arr * 2 #every element of array multiple with 2

array([2, 4, 6, 8])

In [91]:
arr +5

array([6, 7, 8, 9])

In [92]:
arr ** 2  #squre

array([ 1,  4,  9, 16], dtype=int32)

In [93]:
arr **3  #cube

array([ 1,  8, 27, 64], dtype=int32)

In [94]:
arr = np.array([1,2,3,4]).reshape(2,2)
arr

array([[1, 2],
       [3, 4]])

In [95]:
arr * 2

array([[2, 4],
       [6, 8]])

In [96]:
arr + 5

array([[6, 7],
       [8, 9]])

In [97]:
arr ** 2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [98]:
arr ** 3

array([[ 1,  8],
       [27, 64]], dtype=int32)

In [99]:
arr

array([[1, 2],
       [3, 4]])

In [100]:
arr / 1 

array([[1., 2.],
       [3., 4.]])

In [101]:
1/0

ZeroDivisionError: division by zero

In [102]:
#but in numpy we devide  by 0 we dont get error,gets only warning
arr / 0

<ipython-input-102-07b4e499a9c6>:2: RuntimeWarning: divide by zero encountered in true_divide
  arr / 0


array([[inf, inf],
       [inf, inf]])

## operation on 2 or more array

In [103]:
import numpy as np

In [104]:
#1D array
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr3=np.array([9,10,11,12])
#while we perform operation on 2 array ,make sure shape of array's are same otherwise we get error's

In [105]:
arr1+arr2

array([ 6,  8, 10, 12])

In [106]:
arr1+arr2+arr3

array([15, 18, 21, 24])

In [107]:
arr1*arr2

array([ 5, 12, 21, 32])

In [108]:
arr1/arr2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [109]:
arr1**arr2

array([    1,    64,  2187, 65536], dtype=int32)

In [110]:
arr1**arr2+arr3

array([   10,    74,  2198, 65548])

In [111]:
arr1 * arr1

array([ 1,  4,  9, 16])

In [112]:
arr1**arr1

array([  1,   4,  27, 256], dtype=int32)

In [113]:
arr1/arr1

array([1., 1., 1., 1.])

In [114]:
#2D array
np.random.seed(123)
matrix1=np.random.randint(1,12,9).reshape(3,3)
matrix2=np.random.randint(5,15,9).reshape(3,3)

In [115]:
matrix1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [116]:
matrix2

array([[ 5,  6, 14],
       [ 5,  5, 14],
       [ 8,  9,  5]])

In [117]:
#while we perform operation on 2 array ,make sure shape of array's are same otherwise we get error's
matrix1+matrix2

array([[ 8,  9, 21],
       [ 7,  9, 25],
       [18, 16,  7]])

In [118]:
matrix1*matrix2 #this is not actual metrix multiplication

array([[ 15,  18,  98],
       [ 10,  20, 154],
       [ 80,  63,  10]])

In [119]:
matrix1.dot(matrix2) #this is actual metrix multiplication

array([[ 86,  96, 119],
       [118, 131, 139],
       [101, 113, 248]])

## some more useful numpy function 

In [120]:
import numpy as np

In [125]:
arr=np.array([2,80,1,97,5])
arr

array([ 2, 80,  1, 97,  5])

In [126]:
np.min(arr)

1

In [127]:
np.max(arr)

97

In [129]:
np.argmin(arr)#position of min array element

2

In [121]:
np.argmax(arr)

3

In [122]:
np.sqrt(arr)#find squre root 

array([1.41421356, 8.94427191, 1.        , 9.8488578 , 2.23606798])

In [123]:
arr

array([ 2, 80,  1, 97,  5])

In [124]:
np.exp(arr)#euler no^array element = 2.71828^arr,

array([7.38905610e+00, 5.54062238e+34, 2.71828183e+00, 1.33833472e+42,
       1.48413159e+02])

In [125]:
2.71828**2

7.3890461584

In [126]:
np.sin(arr)#gives sin value

array([ 0.90929743, -0.99388865,  0.84147098,  0.37960774, -0.95892427])

In [127]:
np.cos(arr)

array([-0.41614684, -0.11038724,  0.54030231, -0.92514754,  0.28366219])

In [128]:
np.linspace(1,15,5)#give shaperated no's, 5 consider

array([ 1. ,  4.5,  8. , 11.5, 15. ])

In [62]:
mularr = np.arange(1,21).reshape(2,10)
print(mularr)
mulrav = mularr.ravel() # convert multidimensional array into 1D
print(mulrav)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [63]:
mulfla = mularr.flatten() # also convert multidimensional array into 1D
print(mulfla)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


flatten always returns a copy. ravel returns a view of the original array

In [206]:
trans = mularr.transpose() # transpose an array
trans

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19],
       [10, 20]])

In [129]:
arr2 = np.array([1,2,3,0])

In [130]:
arr2

array([1, 2, 3, 0])

In [131]:
arr2 = np.array([1,2,3,0],dtype='bool')

In [132]:
arr2

array([ True,  True,  True, False])

In [133]:
arr2=np.array([1,0,1,1],dtype='bool')

In [134]:
arr2

array([ True, False,  True,  True])

In [135]:
for i in arr2:
    print(i)

True
False
True
True


## numpy axis 

In [136]:
import numpy as np

In [137]:
np.random.seed(123)
matrix=np.random.randint(1,11,9).reshape(3,3)

In [138]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [139]:
np.sum(matrix)

39

In [140]:
matrix.sum()

39

In [141]:
#finding min in every rows and store it in array
np.min(matrix, axis=1)#row wise min,axis=1 for row

array([3, 2, 1])

In [142]:
#finding min in every columns and store it in array
np.min(matrix, axis=0)#column wise min,axis=0 for column

array([2, 2, 1])

In [143]:
#finding man in every rows and store it in array
np.max(matrix, axis=1)#row wise man,axis=1 for row

array([ 7, 10,  7])

In [144]:
#finding min inevery columns and store it in array
np.max(matrix, axis=0)#column wise max,axis=0 for column

array([ 7,  4, 10])

In [145]:
np.sum(matrix, axis=1)

array([13, 16, 10])

In [146]:
#cumelative sum:-3+3=6,6+7=13,13+2=15
np.cumsum(matrix)

array([ 3,  6, 13, 15, 19, 29, 36, 38, 39], dtype=int32)

In [147]:
np.cumsum(matrix, axis=1)#row wise cumelative sum

array([[ 3,  6, 13],
       [ 2,  6, 16],
       [ 7,  9, 10]], dtype=int32)

In [148]:
np.cumsum(matrix, axis=0)#column wise cumelative sum

array([[ 3,  3,  7],
       [ 5,  7, 17],
       [12,  9, 18]], dtype=int32)

In [149]:
np.prod(matrix)

70560

In [150]:
np.prod(matrix, axis=1)

array([63, 80, 14])

In [151]:
np.prod(matrix, axis=0)

array([42, 24, 70])

## shuffle : It shuffle the array element 
## unique : Gives all unique element of array

In [152]:
import numpy as np

In [153]:
np.random.seed(123)
arr=np.random.randint(1,15,15)

In [154]:
arr

array([14,  3, 13,  3,  7,  2,  4, 11, 12, 10,  7,  2,  1,  2, 10])

In [155]:
np.random.shuffle(arr)#shuffle the array element

In [156]:
arr

array([ 4,  2, 11, 12, 13,  2,  3,  7,  1,  2,  7,  3, 10, 10, 14])

In [157]:
np.unique(arr)#all unique element

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

In [158]:
np.unique(arr).size #count unique element

10

In [159]:
np.unique(arr, return_index=True,return_counts=True)#it display position and no of occurrence of element in array

(array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14]),
 array([ 8,  1,  6,  0,  7, 12,  2,  3,  4, 14], dtype=int64),
 array([1, 3, 2, 1, 2, 2, 1, 1, 1, 1], dtype=int64))

## horizontal and vertical stacking 

In [160]:
import numpy as np

In [64]:
np.random.seed(123)
matrix1=np.random.randint(1,20,9).reshape(3,3)
matrix2=np.random.randint(20,40,9).reshape(3,3)

In [162]:
matrix1

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18]])

In [163]:
matrix2

array([[35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [164]:
#horizontal stacking:-Stack arrays in sequence horizontally (column wise).
np.hstack((matrix1, matrix2))

array([[14,  3,  3, 35, 29, 20],
       [ 7, 18, 11, 34, 20, 35],
       [ 2,  1, 18, 39, 34, 24]])

In [165]:
#vertical stacking:-Stack arrays in sequence vertically (column wise). 
np.vstack((matrix1, matrix2))

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18],
       [35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [166]:
#dstack:-Stack arrays in sequence depth wise (along third dimension).
np.dstack((matrix1, matrix2))

array([[[14, 35],
        [ 3, 29],
        [ 3, 20]],

       [[ 7, 34],
        [18, 20],
        [11, 35]],

       [[ 2, 39],
        [ 1, 34],
        [18, 24]]])

In [167]:
#stack:-Join a sequence of arrays along a new axis.(2d)
np.stack((matrix1, matrix2))

array([[[14,  3,  3],
        [ 7, 18, 11],
        [ 2,  1, 18]],

       [[35, 29, 20],
        [34, 20, 35],
        [39, 34, 24]]])

In [168]:
#concatenate:-Join a sequence of arrays along an existing axis
np.concatenate((matrix1, matrix2))

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18],
       [35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

### Horizontal and Vertical Split

In [65]:
matrix1

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18]])

In [67]:
#array_split:-Split an array into multiple sub-arrays of equal or near-equal size. 
#             Does not raise an exception if an equal division cannot be made.
np.array_split(matrix1,3)

[array([[14,  3,  3]]), array([[ 7, 18, 11]]), array([[ 2,  1, 18]])]

In [172]:
# Horizontal split : Split an array horizontally 
np.hsplit(matrix1,3)

[array([[14],
        [ 7],
        [ 2]]),
 array([[ 3],
        [18],
        [ 1]]),
 array([[ 3],
        [11],
        [18]])]

In [173]:
# Vertical Split : Split an array vertically
np.vsplit(matrix1,3)

[array([[14,  3,  3]]), array([[ 7, 18, 11]]), array([[ 2,  1, 18]])]

In [174]:
#dsplit:-Split array into multiple sub-arrays along the 3rd axis (depth),
#        means only work on array of 3 or more dimention
np.dsplit(matrix1,3)

ValueError: dsplit only works on arrays of 3 or more dimensions

In [175]:
array=np.stack((matrix1, matrix2))#3d array
array

array([[[14,  3,  3],
        [ 7, 18, 11],
        [ 2,  1, 18]],

       [[35, 29, 20],
        [34, 20, 35],
        [39, 34, 24]]])

In [176]:
np.dsplit(array,3)

[array([[[14],
         [ 7],
         [ 2]],
 
        [[35],
         [34],
         [39]]]),
 array([[[ 3],
         [18],
         [ 1]],
 
        [[29],
         [20],
         [34]]]),
 array([[[ 3],
         [11],
         [18]],
 
        [[20],
         [35],
         [24]]])]

In [177]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [178]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [179]:
np.vstack((arr1, arr2))

array([[1, 2, 3],
       [4, 5, 6]])

# Excercise
## import numpy library

In [180]:
import numpy as np

## create an array using array function

In [181]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])


## create array containing numbers from 20 to 40

In [182]:
array=np.arange(20,41)
array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

## create array which contain 10 element and every element is 5

In [183]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [184]:
arr[:] = 5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## create 1D array and then convert it into 3D

In [185]:
arr = np.random.randint(1,100,20)
print(arr)
print(arr.ndim)
print(arr.shape)


[97 81 69 50 56 68  3 85 40 67 85 48 62 49  8 93 53 98 86 95]
1
(20,)


In [186]:
arr = arr.reshape(2,2,5) #2*10=20
print(arr)
print(arr.ndim)
print(arr.shape)

[[[97 81 69 50 56]
  [68  3 85 40 67]]

 [[85 48 62 49  8]
  [93 53 98 86 95]]]
3
(2, 2, 5)


## create 2D array which contain random 25 number b/w 0 to 1

In [187]:
arr = np.random.rand(25)

In [188]:
arr

array([0.22826323, 0.29371405, 0.63097612, 0.09210494, 0.43370117,
       0.43086276, 0.4936851 , 0.42583029, 0.31226122, 0.42635131,
       0.89338916, 0.94416002, 0.50183668, 0.62395295, 0.1156184 ,
       0.31728548, 0.41482621, 0.86630916, 0.25045537, 0.48303426,
       0.98555979, 0.51948512, 0.61289453, 0.12062867, 0.8263408 ])

## create array containing 20 random interger then replace every even number with -1
### example:- 
### array:-     [44,55,12,6,3]
### output:-   [-1,55,-1,-1,3]

In [189]:
np.random.seed(123)
array=np.random.randint(1,50,20)
array

array([46,  3, 29, 35, 39, 18, 20, 43, 23, 34, 33, 48, 10, 33, 47, 33, 48,
       26, 20, 15])

In [190]:
array[array%2==0]=-1


In [191]:
array

array([-1,  3, 29, 35, 39, -1, -1, 43, 23, -1, 33, -1, -1, 33, 47, 33, -1,
       -1, -1, 15])

## you have a matrix
#### [[5,10,15,20,25],
#### [30,35,40,45,50],
#### [55,60,65,70,75],
#### [80,85,90,95,100]]

## Extract
#### [30,35,40]
#### [55,60,65]

In [192]:
matrix = np.array([[5,10,15,20,25],[30,35,40,45,50],[55,60,65,70,75],[80,85,90,95,100]])

In [193]:
matrix

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100]])

In [194]:
matrix[1:3,:3]

array([[30, 35, 40],
       [55, 60, 65]])

## concatenate two 1D array

In [195]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [196]:
np.hstack((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

## stack 2D matrix horizontally and vertically

In [197]:
matrix1 = np.array([[5,10,15,20,25],[30,35,40,45,50]])
matrix2 = np.array([[55,60,65,70,75],[80,85,90,95,100]])

In [198]:
matrix1

array([[ 5, 10, 15, 20, 25],
       [30, 35, 40, 45, 50]])

In [199]:
matrix2

array([[ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100]])

In [200]:
np.hstack((matrix1, matrix2))

array([[  5,  10,  15,  20,  25,  55,  60,  65,  70,  75],
       [ 30,  35,  40,  45,  50,  80,  85,  90,  95, 100]])

In [201]:
np.vstack((matrix1, matrix2))

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100]])